export const SET_IS_CREATING_PATH: string = 'SET_IS_CREATING_PATH';
export const UPDATE_PSEUDO_PATH_START_COORDS = 'UPDATE_PSEUDO_PATH_START_COORDS';
export const SET_SELECTED_COMPONENT = 'SET_SELECTED_COMPONENT';