export const SET_IS_CREATING_PATH: string = 'SET_IS_CREATING_PATH';
export const UPDATE_PSEUDO_PATH_START_COORDS: string = 'UPDATE_PSEUDO_PATH_START_COORDS';
export const SET_SELECTED_COMPONENT: string = 'SET_SELECTED_COMPONENT';
export const SET_WEIGHT_OPTION: string = 'SET_WEIGHT_OPTION';
export const SET_DIRECTED_OPTION: string = 'SET_DIRECTED_OPTION';